### PR TITLE
Follow up to #132

### PR DESCRIPTION
**Pull request by thinkbulecount2**
Follow up pull request to https://github.com/oaworks/oa-works/pull/132

Fixed all broken paths to /assets/

### CODE REVIEW

**Comment by sssoz** [comment]
@thinkbulecount2 Thanks for this. Could you resolve the conflict on this branch? 

Also, I’ve run it locally and now nothing is loading — it probably has something to do with `sal.js` which is the library that displays animation. Is this working for you at all locally?

**Comment by sssoz** [comment]
57264e7764508c7e5031b6567f84d270

**Comment by thinkbulecount2** [comment]
@sssoz Yes, it's working; I corrected the paths because originally it was creating it in its own js folder, so I moved it to /assets/js/ -- the same thing happened for me at first. If you try to open the inspector and open the console, what are the errors that come up?

**Comment by sssoz** [comment]
@thinkbulecount2 

````
Failed to load resource: the server responded with a status of 404 (Not Found)
WremenaBold.woff:1          Failed to load resource: the server responded with a status of 404 (Not Found)
Inter.woff2:1          Failed to load resource: the server responded with a status of 404 (Not Found)
jquery-3.6.0.min.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
detect-browser.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
main.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
newsletter.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
bg1.jpg:1          Failed to load resource: the server responded with a status of 404 (Not Found)
jquery-3.6.0.min.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
detect-browser.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
main.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
newsletter.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
latest.source.js:65 Simple Analytics: Set a hostname when sending data from localhost. See https://docs.simpleanalytics.com/overwrite-domain-name
R @ latest.source.js:65
:8080/favicons/favicon.ico?v=1646260995792:1          Failed to load resource: the server responded with a status of 404 (Not Found)
site.webmanifest:1          Failed to load resource: the server responded with a status of 404 (Not Found)
site.webmanifest:1 Manifest: Line: 1, column: 1, Syntax error.
:8080/favicons/favicon-32x32.png?v=1646260995792:1          Failed to load resource: the server responded with a status of 404 (Not Found)
:8080/favicons/favicon-16x16.png?v=1646260995792:1          Failed to load resource: the server responded with a status of 404 (Not Found)
ashley-farley.jpg:1          Failed to load resource: the server responded with a status of 404 (Not Found)
site.webmanifest:1          Failed to load resource: the server responded with a status of 404 (Not Found)
```` 


I usually also delete the contents of the `dist/` directory so that eleventy recompiles everything from scratch.

**Comment by sssoz** [comment]
@thinkbulecount2 Ah looks like it’s because it’s pointing to the live site for the base_url; did you figure out a way to have a local dev setting that overrides these variables?

**Comment by thinkbulecount2** [comment]
I haven't! I'm going to ask around the 11ty Discord! Sorry for the trouble! But if you try to change the base_url, and see if it works?

**Comment by sssoz** [comment]
(As for old code: I realised I hadn’t pulled in the most recent changes, but the issue that images and content aren’t fully loading remains)

Here’s a sample of the stacktrace: 

```
LazyImages - request to https://localhost:8080/assets/img/stories/firefighters.jpg failed, reason: connect ECONNREFUSED ::1:8080: https://localhost:8080/assets/img/stories/firefighters.jpg
LazyImages - request to https://localhost:8080/assets/img/stories/tents.jpg failed, reason: connect ECONNREFUSED ::1:8080: https://localhost:8080/assets/img/stories/tents.jpg
LazyImages - request to https://localhost:8080/assets/img/stories/test-tubes.jpg failed, reason: connect ECONNREFUSED ::1:8080: https://localhost:8080/assets/img/stories/test-tubes.jpg
LazyImages - processed 11 images in dist/index.html
```

**Comment by sssoz** [comment]
> I haven't! I'm going to ask around the 11ty Discord! Sorry for the trouble! But if you try to change the base_url, and see if it works?

https://www.11ty.dev/docs/environment-vars/

**Review by sssoz — CHANGES_REQUESTED** [review]
Looks good and works well, but the conflict still needs to be fixed. Let me know if you need help to do this.

**Comment by thinkbulecount2** [comment]
Yes working on it right now!

**Review by sssoz — APPROVED** [review]

**Comment by sssoz** [comment]
Approved changes for merging — yay @thinkbulecount2 ! 

Just waiting for the tests to run. Could you ensure that all tests pass successfully when you send PRs?

**Comment by thinkbulecount2** [comment]
Will do @sssoz -- tests just passed as well! :)

**Pull request merged**
